/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package medicalimaging.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import medicalimaging.histogramLibrary.Cell;

/**
 *
 * @author Cameron
 */
public class HistogramView extends javax.swing.JPanel {
    
    public ArrayList<Cell> histogram;
    /*
     * Creates new form AnalysisView
     */
    public HistogramView() {
        initComponents();
        histogram = new ArrayList<>();
    }

    public void setHistogram(ArrayList<Cell> h) {
        histogram = h;
        this.repaint();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        
        // Draw the histogram
        int maxValue = 0;
        for ( Cell c : histogram ) {
            maxValue = (int) Math.max(maxValue, Math.abs(c.maxValue));
        }
        
        int xPos = 10;
        for ( Cell c : histogram ) {
            int value = (int) Math.abs(c.maxValue);
            
            float percentage = (float)value / (float)maxValue;
            
            int yOffset = 10;
            int drawHeight = this.getHeight() - 10;
            int barHeight = Math.round(percentage * drawHeight - yOffset);
            int barWidth = (int)this.getWidth() / (int) histogram.size();
            if ( barWidth > 20 ) barWidth = 20;
            
            g.setColor(new Color(50, 50, 50));
            
            int yPos = drawHeight + yOffset - barHeight;
            
            g.fillRect(xPos, yPos, barWidth, barHeight);
            g.setColor(Color.DARK_GRAY);
            g.drawRect(xPos, yPos, barWidth, barHeight);
            xPos += barWidth + 1;
            
            System.out.println("Y Value: " + value);
            
        }
        
        // Do the labels
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
