/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package medicalimaging.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import medicalimaging.histogramLibrary.Cell;

/**
 *
 * @author Cameron
 */
public class HistogramView extends javax.swing.JPanel {
    
    public HashMap<String, Integer> histogram;
    /*
     * Creates new form AnalysisView
     */
    public HistogramView() {
        initComponents();
        histogram = new HashMap<>();
    }

    public void setHistogram(HashMap<String, Integer> h) {
        histogram = h;
        this.repaint();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        Object[] akeys = histogram.keySet().toArray();
        int[] intKeys = new int[akeys.length];
        for ( int j = 0; j < akeys.length; j++ ) {
            intKeys[j] = Integer.parseInt((String)akeys[j]);
        }
        
        Arrays.sort(intKeys);
        
        // Draw the histogram
        int maxValue = 0;
        for ( int x : intKeys ) {
            maxValue = (int) Math.max(maxValue, histogram.get("" + x));
        }
        
        int prevX = -1;
        int xPos = 10;
        for ( int x : intKeys ) {
            int value = (int) histogram.get("" + x);
            
            float percentage = (float)value / (float)maxValue;
            
            int yOffset = 0;
            int drawHeight = this.getHeight() - 10;
            int barHeight = Math.round(percentage * drawHeight - yOffset);
            int barWidth = (int)(this.getWidth()-30) / (int) (intKeys.length + 1);
            if ( barWidth > 30 ) barWidth = 30;
            
            g.setColor(new Color(50, 50, 50));
            
            int yPos = drawHeight + yOffset - barHeight - 20;
            
            g.fillRect(xPos, yPos, barWidth, barHeight);
            g.setColor(Color.DARK_GRAY);
            g.drawRect(xPos, yPos, barWidth, barHeight);
            
            g.setColor(Color.BLUE);
            
            if ( prevX < xPos - 30 || prevX == -1) {
                g.drawString("" + x, xPos, drawHeight - 8);
                prevX = xPos;
            }
            
            
            
            xPos += barWidth + 1;
            
        }
        
        // Do the labels
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
