/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package medicalimaging;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author ericlee
 */
public class MainFrame extends javax.swing.JFrame implements TreeSelectionListener, MouseWheelListener{

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        //Configure study tree
        studyTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        studyTree.addTreeSelectionListener(this);
        
        //Configure image panel
        imagePanel.setLayout(new GridLayout(0,1));
        imagePanel.addMouseWheelListener(this);
        //this.addMouseWheelListener(this);
        JLabel placeHolder = new JLabel("");
        placeHolder.setPreferredSize(new Dimension(imagePanel.getWidth(), imagePanel.getWidth()));
        imagePanel.add(placeHolder);
    }
    
    /**
     * Load images into the JPanel
     * @param loadImages ArrayList<MedicalImage> to load
     */
    protected void loadImages(ArrayList<MedicalImage> loadImages) {
        this.clearImagePanel();
        double  sqrt = Math.sqrt(loadImages.size());
        int gridSize = (int)Math.ceil(sqrt);
        this.imagePanel.setLayout(new GridLayout(gridSize, gridSize));
        
        
        for(MedicalImage loadImage : loadImages) {
            int imageWidth = this.imagePanel.getWidth() / gridSize;//gridDivider;
            int imageHeight = this.imagePanel.getHeight() / gridSize;//gridDivider;
            ImageIcon tempIcon = loadImage.loadImage();
            Image image = tempIcon.getImage();
            Image scaledImage = image.getScaledInstance(imageWidth, imageHeight, 0);
            Icon imageIcon = new ImageIcon(scaledImage);
            JLabel imageLabel = new JLabel(imageIcon);
            this.imagePanel.add(imageLabel);
        }
        
        //Load placeholders
        /*for(int i = 0; i < Math.pow(gridSize, 2) - loadImages.size(); i++) {
            ImageIcon tempIcon = loadImages.get(0).loadImage();
            Image image = tempIcon.getImage();
            Image scaledImage = image.getScaledInstance(imagePanel.getWidth() / gridSize, imagePanel.getHeight() / gridSize, 0);
            Icon imageIcon = new ImageIcon(scaledImage);
            JLabel imageLabel = new JLabel(imageIcon);
            this.imagePanel.add(imageLabel);
        }*/
        
        this.imagePanel.revalidate();
    }
    
    protected void setTreeModel(TreeModel model) {
        studyTree.setModel(model);
    }
    
    protected void refreshImages() {
        this.valueChanged(null);
    }
    
    /**
     * Removes all images from the image JPanel
     */
    private void clearImagePanel() {
        Component[] components = this.imagePanel.getComponents();
        for(Component curComponent : components) {
            this.imagePanel.remove(curComponent);
        }
    }
    
    @Override
    public void mouseWheelMoved(MouseWheelEvent e) {
        int mouseX = e.getX();
        int mouseY = e.getY();
        int panelX = imagePanel.getX();
        int panelY = imagePanel.getY();
        
        //if((mouseX > panelX && mouseX < panelX + imagePanel.getWidth()) && (mouseY > panelY && mouseY < imagePanel.getHeight())) {
            int notches = e.getWheelRotation();
            Component[] components = imagePanel.getComponents();
            Component hoverComponent = imagePanel.getComponentAt(e.getPoint());
            
            System.out.println(hoverComponent);
            int hoverIndex = Arrays.asList(components).indexOf(hoverComponent);
            delegate.mouseScrollOnImage(notches, hoverIndex);
        //}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studyTreePanel = new javax.swing.JScrollPane();
        studyTree = new javax.swing.JTree();
        imagePanel = new javax.swing.JPanel();
        toolbar = new javax.swing.JToolBar();
        openButton = new javax.swing.JButton();
        copyButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        displayModeSelect = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studyTreePanel.setViewportView(studyTree);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        toolbar.setRollover(true);

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalimaging/open.gif"))); // NOI18N
        openButton.setFocusable(false);
        openButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        toolbar.add(openButton);

        copyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalimaging/copy.gif"))); // NOI18N
        copyButton.setFocusable(false);
        copyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });
        toolbar.add(copyButton);

        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalimaging/previous.gif"))); // NOI18N
        previousButton.setFocusable(false);
        previousButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        toolbar.add(previousButton);

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalimaging/next.gif"))); // NOI18N
        nextButton.setFocusable(false);
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        toolbar.add(nextButton);

        undoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalimaging/undo.gif"))); // NOI18N
        undoButton.setFocusable(false);
        undoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        undoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });
        toolbar.add(undoButton);

        displayModeSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1x1", "2x2", "Recon"}));
        displayModeSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayModeSelectActionPerformed(evt);
            }
        });
        toolbar.add(displayModeSelect);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studyTreePanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(studyTreePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        delegate.previousButtonPressed();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        delegate.loadStudyButtonPressed();
    }//GEN-LAST:event_openButtonActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        delegate.copyButtonPressed();
    }//GEN-LAST:event_copyButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        delegate.nextButtonPressed();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        delegate.undoButtonPressed();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void displayModeSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayModeSelectActionPerformed
        String selectedItem = (String)displayModeSelect.getSelectedItem();
        int displayMode = Study.DISPLAY_MODE_1x1;
        if(selectedItem.equals("2x2"))
            displayMode = Study.DISPLAY_MODE_2x2;
        else if(selectedItem.equals("Recon"))
            displayMode = Study.DISPLAY_MODE_RECON;
        delegate.displayModeChanged(displayMode);
    }//GEN-LAST:event_displayModeSelectActionPerformed
    
    /**
     * Executes when the value of the JTree is changed
     * TODO: This method should be cleaned up and sized down.
     * @param e 
     */
    @Override
    public void valueChanged(TreeSelectionEvent e) {
        delegate.selectedImageChanged((StudyElement)studyTree.getLastSelectedPathComponent());
    }
    
    public void updateGUIForState(int state) {
        if(state == Study.DISPLAY_MODE_1x1)
            displayModeSelect.setSelectedItem("1x1");
        else if(state == Study.DISPLAY_MODE_2x2)
            displayModeSelect.setSelectedItem("2x2");
        else
            displayModeSelect.setSelectedItem("Recon");
    }
    
    protected MainFrameViewProtocol delegate;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyButton;
    protected javax.swing.JComboBox displayModeSelect;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton previousButton;
    protected javax.swing.JTree studyTree;
    private javax.swing.JScrollPane studyTreePanel;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables

}
